//! Small filesystem helpers for the local executor.
//!
//! This file owns the crash-safe write path and the follow-up cleanup around
//! deletes so session orchestration can stay small and readable.
//!
//! Crash-safe replace flow:
//!
//!   source bytes / generated bytes
//!               |
//!               v
//!     sibling temp file in destination dir
//!               |
//!               v
//!      fsync temp + apply final metadata
//!               |
//!               v
//!      rename temp over destination atomically
//!               |
//!               v
//!          fsync parent directory

use std::ffi::OsString;
use std::fs::{self, File, Metadata, OpenOptions};
use std::io;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use crate::error::SessionError;

static TEMP_FILE_COUNTER: AtomicU64 = AtomicU64::new(0);

/// Replace `destination` with the contents and basic metadata from `source`.
///
/// The write happens through a sibling temp file so a crash does not leave a
/// truncated destination file behind.
pub fn replace_file(source: &Path, destination: &Path) -> Result<(), SessionError> {
    let mut source_file = File::open(source).map_err(|source_error| SessionError::ApplyIo {
        operation: "open source file",
        path: source.to_path_buf(),
        source: source_error,
    })?;

    replace_with_writer(source, destination, |writer| {
        io::copy(&mut source_file, writer).map_err(|source_error| SessionError::ApplyIo {
            operation: "copy file data into temporary destination",
            path: destination.to_path_buf(),
            source: source_error,
        })?;

        Ok(())
    })
}

/// Replace `destination` with generated bytes while preserving metadata copied
/// from `source_metadata_path`.
pub fn replace_with_writer(
    source_metadata_path: &Path,
    destination: &Path,
    write_contents: impl FnOnce(&mut File) -> Result<(), SessionError>,
) -> Result<(), SessionError> {
    // The executor hands us a writer closure so strategy code can stream bytes
    // into a temp file without knowing anything about temp-file naming, rename
    // rules, or parent-directory syncing.
    let parent = parent_directory(destination);
    fs::create_dir_all(parent).map_err(|source_error| SessionError::ApplyIo {
        operation: "create destination parent directory",
        path: parent.to_path_buf(),
        source: source_error,
    })?;

    let source_metadata =
        fs::metadata(source_metadata_path).map_err(|source_error| SessionError::ApplyIo {
            operation: "read source metadata",
            path: source_metadata_path.to_path_buf(),
            source: source_error,
        })?;

    let mut pending = PendingFile::create(destination)?;
    write_contents(pending.file(destination)?)?;
    apply_metadata(pending.file(destination)?, &source_metadata, destination)?;
    pending.persist(destination)
}

/// Apply metadata-only changes to an existing file without rewriting contents.
pub fn sync_metadata(source: &Path, destination: &Path) -> Result<(), SessionError> {
    let source_metadata = fs::metadata(source).map_err(|source_error| SessionError::ApplyIo {
        operation: "read source metadata",
        path: source.to_path_buf(),
        source: source_error,
    })?;
    let destination_file =
        File::options()
            .read(true)
            .open(destination)
            .map_err(|source_error| SessionError::ApplyIo {
                operation: "open destination file for metadata update",
                path: destination.to_path_buf(),
                source: source_error,
            })?;

    apply_metadata(&destination_file, &source_metadata, destination)?;
    destination_file
        .sync_all()
        .map_err(|source_error| SessionError::ApplyIo {
            operation: "sync destination file metadata",
            path: destination.to_path_buf(),
            source: source_error,
        })?;

    Ok(())
}

pub fn remove_file(path: &Path) -> Result<(), SessionError> {
    fs::remove_file(path).map_err(|source_error| SessionError::ApplyIo {
        operation: "remove destination file",
        path: path.to_path_buf(),
        source: source_error,
    })?;
    sync_parent_directory(path)
}

/// Remove empty parent directories after deleting a file, but keep the sync
/// root itself so directory-target syncs do not disappear entirely.
pub fn prune_empty_parent_directories(path: &Path, root: &Path) -> Result<(), SessionError> {
    let mut current = parent_directory(path);

    while current.starts_with(root) && current != root {
        match fs::remove_dir(current) {
            Ok(()) => {
                sync_parent_directory(current)?;
                current = parent_directory(current);
            }
            Err(source_error) if source_error.kind() == io::ErrorKind::DirectoryNotEmpty => {
                break;
            }
            Err(source_error) if source_error.kind() == io::ErrorKind::NotFound => {
                break;
            }
            Err(source_error) => {
                return Err(SessionError::ApplyIo {
                    operation: "remove empty destination directory",
                    path: current.to_path_buf(),
                    source: source_error,
                });
            }
        }
    }

    Ok(())
}

fn apply_metadata(
    file: &File,
    metadata: &Metadata,
    destination: &Path,
) -> Result<(), SessionError> {
    file.set_permissions(metadata.permissions())
        .map_err(|source_error| SessionError::ApplyIo {
            operation: "set file permissions",
            path: destination.to_path_buf(),
            source: source_error,
        })?;

    if let Ok(modified) = metadata.modified() {
        file.set_modified(modified)
            .map_err(|source_error| SessionError::ApplyIo {
                operation: "set file modified time",
                path: destination.to_path_buf(),
                source: source_error,
            })?;
    }

    Ok(())
}

fn parent_directory(path: &Path) -> &Path {
    path.parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or(Path::new("."))
}

fn sync_parent_directory(path: &Path) -> Result<(), SessionError> {
    #[cfg(unix)]
    {
        let parent = parent_directory(path);
        let directory = File::open(parent).map_err(|source_error| SessionError::ApplyIo {
            operation: "open parent directory for sync",
            path: parent.to_path_buf(),
            source: source_error,
        })?;

        directory
            .sync_all()
            .map_err(|source_error| SessionError::ApplyIo {
                operation: "sync parent directory",
                path: parent.to_path_buf(),
                source: source_error,
            })?;
    }

    #[cfg(not(unix))]
    {
        let _ = path;
    }

    Ok(())
}

struct PendingFile {
    path: PathBuf,
    file: Option<File>,
    persisted: bool,
}

impl PendingFile {
    fn create(destination: &Path) -> Result<Self, SessionError> {
        let parent = parent_directory(destination);
        let file_name = destination
            .file_name()
            .map(OsString::from)
            .unwrap_or_else(|| OsString::from("oni-target"));

        for _ in 0..128 {
            let unique = TEMP_FILE_COUNTER.fetch_add(1, Ordering::Relaxed);
            let temp_name = format!(
                ".{}.oni-tmp-{}-{}",
                file_name.to_string_lossy(),
                std::process::id(),
                unique
            );
            let temp_path = parent.join(temp_name);

            match OpenOptions::new()
                .write(true)
                .create_new(true)
                .open(&temp_path)
            {
                Ok(file) => {
                    return Ok(Self {
                        path: temp_path,
                        file: Some(file),
                        persisted: false,
                    });
                }
                Err(source_error) if source_error.kind() == io::ErrorKind::AlreadyExists => {
                    continue;
                }
                Err(source_error) => {
                    return Err(SessionError::ApplyIo {
                        operation: "create temporary destination file",
                        path: destination.to_path_buf(),
                        source: source_error,
                    });
                }
            }
        }

        Err(SessionError::ApplyIo {
            operation: "create temporary destination file",
            path: destination.to_path_buf(),
            source: io::Error::other("exhausted temporary file name attempts"),
        })
    }

    fn file(&mut self, destination: &Path) -> Result<&mut File, SessionError> {
        self.file.as_mut().ok_or_else(|| SessionError::ApplyIo {
            operation: "access temporary destination file",
            path: destination.to_path_buf(),
            source: io::Error::other("temporary file handle unexpectedly missing"),
        })
    }

    fn persist(mut self, destination: &Path) -> Result<(), SessionError> {
        let file = take_pending_file(
            &mut self.file,
            &self.path,
            "sync temporary destination file",
        )?;
        file.sync_all()
            .map_err(|source_error| SessionError::ApplyIo {
                operation: "sync temporary destination file",
                path: self.path.clone(),
                source: source_error,
            })?;
        drop(file);

        fs::rename(&self.path, destination).map_err(|source_error| SessionError::ApplyIo {
            operation: "rename temporary file into place",
            path: destination.to_path_buf(),
            source: source_error,
        })?;
        self.persisted = true;
        sync_parent_directory(destination)
    }
}

fn take_pending_file(
    slot: &mut Option<File>,
    path: &Path,
    operation: &'static str,
) -> Result<File, SessionError> {
    slot.take().ok_or_else(|| SessionError::ApplyIo {
        operation,
        path: path.to_path_buf(),
        source: io::Error::other("temporary file handle unexpectedly missing"),
    })
}

impl Drop for PendingFile {
    fn drop(&mut self) {
        if self.persisted {
            return;
        }

        if let Some(file) = self.file.take() {
            drop(file);
        }

        let _ = fs::remove_file(&self.path);
    }
}
